# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60f0ce9e60e1b62ae306a661d1a181776f2b63a042c1e2864ccfce9da149c246b9bb6df698746751875cbaffbd4be3fcde87104d79acd33e57532f569da8bff6

test:
  secret_key_base: 9583a88b66d1970d24afa0e0e5cc4e1d92ca47510ce52debb25b9a1f4c5459ef32d2932e799c54d4f09e7283d743ff69f427c9f260865786de4e6987b9d65cf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
